### ISSUE TITLE
"local-uri"/"local-part" and "REST-method-set"

### ISSUE THREAD

**Issue by ektrah** [cabo/ace-aif#4]
https://github.com/cabo/ace-aif/blob/dc362c1b8bab486c9e9891d29f3887f0ed1b94cb/draft-ietf-ace-aif.md?plain=1#L378-L387

It seems that "local-uri" (or "local-part") and "REST-method-set" are nowhere properly defined.

Should the default values be "path" and "permissions", which are defined in [Section 3](https://datatracker.ietf.org/doc/html/draft-ietf-ace-aif-05#section-3)?

https://github.com/cabo/ace-aif/blob/dc362c1b8bab486c9e9891d29f3887f0ed1b94cb/draft-ietf-ace-aif.md?plain=1#L289-L290

**Comment by cabo** [comment]
The intention was that Section 4 was to provide this definition.
But indeed that is a bit thin.
Also the confusion between `local-part` and `local-uri` is unfortunate.
(It can't be `local-uri` as this isn't a full URI.
`local-part` is a bit nondescript.)

Maybe the CDDL names should also be closer to the parameter names; the current names are not that useful outside the CDDL model.
